name: Build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '4/15 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout PR maker   
        uses: actions/checkout@v2
        with:
            path: pr-maker

      - name: Checkout TW branch tiddlywiki-com
        uses: actions/checkout@v2
        with:
            repository: TiddlyWiki/TiddlyWiki5
            ref: tiddlywiki-com
            path: tiddlywiki

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Build
        run: |
            cp -fr ./pr-maker/plugins ./tiddlywiki/editions/tw5.com/plugins
            node tiddlywiki/tiddlywiki ./tiddlywiki/editions/tw5.com --output ./output --build index
            ls

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output
          keep_files: true   
